In [2]:
import cv2
import numpy as np
from numba import njit

seed = (0, 0)

# Note: it is not possible to use the numba package, since it not interpret
# the python form of rgb image required in the question
def region_growing(image, seed=None):

    # Get the rows and columns of the image
    rows, cols = image.shape[:2]

    # Get the seed point
    xc, yc = seed

    # Create a matrix that will contain the segmented region
    segmented = np.zeros_like(image)

    # Reference Color and Mark the seed point in the image
    ref_color = image[xc, yc]
    segmented[xc, yc] = ref_color

    # Loop through the image until the region stop growing
    current_found = 0
    previous_points = 1

    while previous_points != current_found:

        previous_points = current_found
        current_found = 0
        for row in range(rows):
            for col in range(cols):
                # Verify if we reach the ROI and search through the neighborhood to see if the pixel is of the same
                # object, then if the pixel is part of the object put them in the segmented image
                k = segmented[row, col]
                if np.all(k==ref_color):
                    if np.all(image[row - 1, col - 1]==ref_color):
                        segmented[row - 1, col - 1] = ref_color
                        current_found += 1
                    if np.all(image[row - 1, col]== ref_color):
                        segmented[row - 1, col] = ref_color
                        current_found += 1
                    if np.all(image[row - 1, col + 1]== ref_color):
                        segmented[row - 1, col + 1] = ref_color
                        current_found += 1
                    if np.all(image[row, col - 1]== ref_color):
                        segmented[row, col - 1] = ref_color
                        current_found += 1
                    if np.all(image[row, col + 1]== ref_color):
                        segmented[row, col + 1] = ref_color
                        current_found += 1
                    if np.all(image[row + 1, col - 1]== ref_color):
                        segmented[row + 1, col - 1] = ref_color
                        current_found += 1
                    if np.all(image[row + 1, col]== ref_color):
                        segmented[row + 1, col] = ref_color
                        current_found += 1
                    if np.all(image[row + 1, col + 1]== ref_color):
                        segmented[row + 1, col + 1] = ref_color
                        current_found += 1

    return segmented


def mouse_event(event, x, y, flags, param):
    # Verify if the left button is pressed
    if event == cv2.EVENT_LBUTTONDOWN:
        global seed

        # Update the seed point
        seed = (y, x)

if __name__ == '__main__':
    # Read a rgb image
    image = cv2.imread('estrela.png')
    # The code is VERY SLOW ... so let's resize the image
    image = cv2.resize(image, (0, 0), fx=0.3, fy=0.3)

    # Create a window, show the original image and wait for the click
    cv2.namedWindow('Original Image', 1)
    cv2.imshow('Original Image', image)
    cv2.setMouseCallback('Original Image', mouse_event)
    cv2.waitKey(0)

    # Apply the region growing algorithm
    segmented_image = region_growing(image, seed)
    print(segmented_image)
    
    '''
    # Segmented image - centroid
    x_c=0
    y_c=0
    total=0
    rows, cols = grayscale_image.shape
    for row in range(rows):
        for col in range(cols):
            if backtorgb[row, col][0] == 255 and backtorgb[row, col][1] == 255 and backtorgb[row, col][2] == 255:
                x_c+=col
                y_c+=row
                total=total+1
                backtorgb[row, col] = (255,0,0) # blue, green, red
    
    x_c=int(x_c/total)
    y_c=int(y_c/total)
    
    # Draw a circle in the centroid of the square
    cv2.circle(backtorgb, (x_c, y_c), 5, (0, 255, 0),-1)
    '''
    
    # Show the result
    cv2.imshow('Segmented image', segmented_image)
    cv2.imwrite('segmented_image.jpg', segmented_image)
    cv2.waitKey(0)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
